# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fortran-Format
version:      0.90
version_from: Format.pm
installdirs:  site
requires:
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
